/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.parser;

import minijava.node.*;
import minijava.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTTokNumber(@SuppressWarnings("unused") TTokNumber node)
    {
        this.index = 0;
    }

    @Override
    public void caseTTokLparen(@SuppressWarnings("unused") TTokLparen node)
    {
        this.index = 1;
    }

    @Override
    public void caseTTokRparen(@SuppressWarnings("unused") TTokRparen node)
    {
        this.index = 2;
    }

    @Override
    public void caseTTokLbracket(@SuppressWarnings("unused") TTokLbracket node)
    {
        this.index = 3;
    }

    @Override
    public void caseTTokRbracket(@SuppressWarnings("unused") TTokRbracket node)
    {
        this.index = 4;
    }

    @Override
    public void caseTTokLkey(@SuppressWarnings("unused") TTokLkey node)
    {
        this.index = 5;
    }

    @Override
    public void caseTTokRkey(@SuppressWarnings("unused") TTokRkey node)
    {
        this.index = 6;
    }

    @Override
    public void caseTTokIf(@SuppressWarnings("unused") TTokIf node)
    {
        this.index = 7;
    }

    @Override
    public void caseTTokElse(@SuppressWarnings("unused") TTokElse node)
    {
        this.index = 8;
    }

    @Override
    public void caseTTokClass(@SuppressWarnings("unused") TTokClass node)
    {
        this.index = 9;
    }

    @Override
    public void caseTTokPublic(@SuppressWarnings("unused") TTokPublic node)
    {
        this.index = 10;
    }

    @Override
    public void caseTTokStatic(@SuppressWarnings("unused") TTokStatic node)
    {
        this.index = 11;
    }

    @Override
    public void caseTTokVoid(@SuppressWarnings("unused") TTokVoid node)
    {
        this.index = 12;
    }

    @Override
    public void caseTTokMain(@SuppressWarnings("unused") TTokMain node)
    {
        this.index = 13;
    }

    @Override
    public void caseTTokString(@SuppressWarnings("unused") TTokString node)
    {
        this.index = 14;
    }

    @Override
    public void caseTTokInt(@SuppressWarnings("unused") TTokInt node)
    {
        this.index = 15;
    }

    @Override
    public void caseTTokIntarray(@SuppressWarnings("unused") TTokIntarray node)
    {
        this.index = 16;
    }

    @Override
    public void caseTTokBoolean(@SuppressWarnings("unused") TTokBoolean node)
    {
        this.index = 17;
    }

    @Override
    public void caseTTokExtends(@SuppressWarnings("unused") TTokExtends node)
    {
        this.index = 18;
    }

    @Override
    public void caseTTokSemicolon(@SuppressWarnings("unused") TTokSemicolon node)
    {
        this.index = 19;
    }

    @Override
    public void caseTTokComma(@SuppressWarnings("unused") TTokComma node)
    {
        this.index = 20;
    }

    @Override
    public void caseTTokDot(@SuppressWarnings("unused") TTokDot node)
    {
        this.index = 21;
    }

    @Override
    public void caseTTokReturn(@SuppressWarnings("unused") TTokReturn node)
    {
        this.index = 22;
    }

    @Override
    public void caseTTokWhile(@SuppressWarnings("unused") TTokWhile node)
    {
        this.index = 23;
    }

    @Override
    public void caseTTokSyso(@SuppressWarnings("unused") TTokSyso node)
    {
        this.index = 24;
    }

    @Override
    public void caseTTokEqual(@SuppressWarnings("unused") TTokEqual node)
    {
        this.index = 25;
    }

    @Override
    public void caseTTokAnd(@SuppressWarnings("unused") TTokAnd node)
    {
        this.index = 26;
    }

    @Override
    public void caseTTokLess(@SuppressWarnings("unused") TTokLess node)
    {
        this.index = 27;
    }

    @Override
    public void caseTTokPlus(@SuppressWarnings("unused") TTokPlus node)
    {
        this.index = 28;
    }

    @Override
    public void caseTTokMinus(@SuppressWarnings("unused") TTokMinus node)
    {
        this.index = 29;
    }

    @Override
    public void caseTTokTimes(@SuppressWarnings("unused") TTokTimes node)
    {
        this.index = 30;
    }

    @Override
    public void caseTTokLength(@SuppressWarnings("unused") TTokLength node)
    {
        this.index = 31;
    }

    @Override
    public void caseTTokTrue(@SuppressWarnings("unused") TTokTrue node)
    {
        this.index = 32;
    }

    @Override
    public void caseTTokFalse(@SuppressWarnings("unused") TTokFalse node)
    {
        this.index = 33;
    }

    @Override
    public void caseTTokThis(@SuppressWarnings("unused") TTokThis node)
    {
        this.index = 34;
    }

    @Override
    public void caseTTokNew(@SuppressWarnings("unused") TTokNew node)
    {
        this.index = 35;
    }

    @Override
    public void caseTTokExclamation(@SuppressWarnings("unused") TTokExclamation node)
    {
        this.index = 36;
    }

    @Override
    public void caseTTokId(@SuppressWarnings("unused") TTokId node)
    {
        this.index = 37;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 38;
    }
}
