/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.lexer;

import java.io.*;
import minijava.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private PushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") PushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        int middle = (low + high) / 2;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTokNumber(text, line, pos); }
    Token new1(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTokLparen(line, pos); }
    Token new2(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTokRparen(line, pos); }
    Token new3(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTokLbracket(line, pos); }
    Token new4(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTokRbracket(line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTokLkey(line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTokRkey(line, pos); }
    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTokIf(line, pos); }
    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTokElse(line, pos); }
    Token new9(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTokClass(line, pos); }
    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTokPublic(line, pos); }
    Token new11(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTokStatic(line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTokVoid(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTokMain(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTokString(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTokInt(line, pos); }
    Token new16(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTokIntarray(text, line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTokBoolean(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTokExtends(line, pos); }
    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTokSemicolon(line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTokComma(line, pos); }
    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTokDot(line, pos); }
    Token new22(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTokReturn(line, pos); }
    Token new23(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTokWhile(line, pos); }
    Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTokSyso(line, pos); }
    Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTokEqual(line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTokAnd(line, pos); }
    Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTokLess(line, pos); }
    Token new28(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTokPlus(line, pos); }
    Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTokMinus(line, pos); }
    Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTokTimes(line, pos); }
    Token new31(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTokLength(line, pos); }
    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTokTrue(line, pos); }
    Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTokFalse(line, pos); }
    Token new34(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTokThis(line, pos); }
    Token new35(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTokNew(line, pos); }
    Token new36(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTokExclamation(line, pos); }
    Token new37(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTokBlank(text, line, pos); }
    Token new38(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTokComment(text, line, pos); }
    Token new39(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTokId(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {33, 33, 5}, {38, 38, 6}, {40, 40, 7}, {41, 41, 8}, {42, 42, 9}, {43, 43, 10}, {44, 44, 11}, {45, 45, 12}, {46, 46, 13}, {47, 47, 14}, {48, 57, 15}, {59, 59, 16}, {60, 60, 17}, {61, 61, 18}, {65, 82, 19}, {83, 83, 20}, {84, 90, 19}, {91, 91, 21}, {93, 93, 22}, {97, 97, 23}, {98, 98, 24}, {99, 99, 25}, {100, 100, 23}, {101, 101, 26}, {102, 102, 27}, {103, 104, 23}, {105, 105, 28}, {106, 107, 23}, {108, 108, 29}, {109, 109, 30}, {110, 110, 31}, {111, 111, 23}, {112, 112, 32}, {113, 113, 23}, {114, 114, 33}, {115, 115, 34}, {116, 116, 35}, {117, 117, 23}, {118, 118, 36}, {119, 119, 37}, {120, 122, 23}, {123, 123, 38}, {125, 125, 39}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 9, 1}, {10, 10, 40}, {13, 32, -2}, },
            {{9, 32, -2}, },
            {},
            {{38, 38, 41}, },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {{42, 42, 42}, {47, 47, 43}, },
            {{48, 57, 15}, },
            {},
            {},
            {},
            {{48, 57, 44}, {65, 90, 45}, {95, 95, 46}, {97, 122, 47}, },
            {{48, 95, -21}, {97, 115, 47}, {116, 116, 48}, {117, 120, 47}, {121, 121, 49}, {122, 122, 47}, },
            {},
            {},
            {{48, 122, -21}, },
            {{48, 95, -21}, {97, 110, 47}, {111, 111, 50}, {112, 122, 47}, },
            {{48, 95, -21}, {97, 107, 47}, {108, 108, 51}, {109, 122, 47}, },
            {{48, 107, -27}, {108, 108, 52}, {109, 119, 47}, {120, 120, 53}, {121, 122, 47}, },
            {{48, 95, -21}, {97, 97, 54}, {98, 122, 47}, },
            {{48, 95, -21}, {97, 101, 47}, {102, 102, 55}, {103, 109, 47}, {110, 110, 56}, {111, 122, 47}, },
            {{48, 95, -21}, {97, 100, 47}, {101, 101, 57}, {102, 122, 47}, },
            {{48, 95, -21}, {97, 97, 58}, {98, 122, 47}, },
            {{48, 100, -31}, {101, 101, 59}, {102, 122, 47}, },
            {{48, 95, -21}, {97, 116, 47}, {117, 117, 60}, {118, 122, 47}, },
            {{48, 100, -31}, {101, 101, 61}, {102, 122, 47}, },
            {{48, 115, -22}, {116, 116, 62}, {117, 122, 47}, },
            {{48, 95, -21}, {97, 103, 47}, {104, 104, 63}, {105, 113, 47}, {114, 114, 64}, {115, 122, 47}, },
            {{48, 110, -26}, {111, 111, 65}, {112, 122, 47}, },
            {{48, 103, -37}, {104, 104, 66}, {105, 122, 47}, },
            {},
            {},
            {{9, 32, -2}, },
            {},
            {{0, 41, 67}, {42, 42, 68}, {43, 65535, 67}, },
            {{0, 9, 69}, {10, 10, 70}, {11, 12, 69}, {13, 13, 71}, {14, 65535, 69}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 95, -21}, {97, 113, 47}, {114, 114, 72}, {115, 122, 47}, },
            {{48, 95, -21}, {97, 114, 47}, {115, 115, 73}, {116, 122, 47}, },
            {{48, 110, -26}, {111, 111, 74}, {112, 122, 47}, },
            {{48, 95, -21}, {97, 97, 75}, {98, 122, 47}, },
            {{48, 114, -51}, {115, 115, 76}, {116, 122, 47}, },
            {{48, 115, -22}, {116, 116, 77}, {117, 122, 47}, },
            {{48, 107, -27}, {108, 108, 78}, {109, 122, 47}, },
            {{48, 122, -21}, },
            {{48, 115, -22}, {116, 116, 79}, {117, 122, 47}, },
            {{48, 95, -21}, {97, 109, 47}, {110, 110, 80}, {111, 122, 47}, },
            {{48, 95, -21}, {97, 104, 47}, {105, 105, 81}, {106, 122, 47}, },
            {{48, 95, -21}, {97, 118, 47}, {119, 119, 82}, {120, 122, 47}, },
            {{48, 95, -21}, {97, 97, 47}, {98, 98, 83}, {99, 122, 47}, },
            {{48, 115, -22}, {116, 116, 84}, {117, 122, 47}, },
            {{48, 95, -21}, {97, 97, 85}, {98, 122, 47}, },
            {{48, 104, -60}, {105, 105, 86}, {106, 122, 47}, },
            {{48, 116, -34}, {117, 117, 87}, {118, 122, 47}, },
            {{48, 104, -60}, {105, 105, 88}, {106, 122, 47}, },
            {{48, 104, -60}, {105, 105, 89}, {106, 122, 47}, },
            {{0, 65535, -44}, },
            {{0, 41, 90}, {42, 42, 68}, {43, 46, 90}, {47, 47, 91}, {48, 65535, 90}, },
            {{0, 65535, -45}, },
            {},
            {{10, 10, 92}, },
            {{48, 104, -60}, {105, 105, 93}, {106, 122, 47}, },
            {{48, 115, -22}, {116, 116, 94}, {117, 122, 47}, },
            {{48, 107, -27}, {108, 108, 95}, {109, 122, 47}, },
            {{48, 114, -51}, {115, 115, 96}, {116, 122, 47}, },
            {{48, 100, -31}, {101, 101, 97}, {102, 122, 47}, },
            {{48, 100, -31}, {101, 101, 98}, {102, 122, 47}, },
            {{48, 114, -51}, {115, 115, 99}, {116, 122, 47}, },
            {{9, 9, 100}, {32, 32, 101}, {48, 90, -21}, {91, 91, 102}, {95, 122, -21}, },
            {{48, 95, -21}, {97, 102, 47}, {103, 103, 103}, {104, 122, 47}, },
            {{48, 109, -59}, {110, 110, 104}, {111, 122, 47}, },
            {{48, 122, -21}, },
            {{48, 107, -27}, {108, 108, 105}, {109, 122, 47}, },
            {{48, 116, -34}, {117, 117, 106}, {118, 122, 47}, },
            {{48, 115, -22}, {116, 116, 107}, {117, 122, 47}, },
            {{48, 114, -51}, {115, 115, 108}, {116, 122, 47}, },
            {{48, 100, -31}, {101, 101, 109}, {102, 122, 47}, },
            {{48, 95, -21}, {97, 99, 47}, {100, 100, 110}, {101, 122, 47}, },
            {{48, 107, -27}, {108, 108, 111}, {109, 122, 47}, },
            {{0, 41, 112}, {42, 42, 113}, {43, 65535, 112}, },
            {},
            {},
            {{48, 109, -59}, {110, 110, 114}, {111, 122, 47}, },
            {{48, 100, -31}, {101, 101, 115}, {102, 122, 47}, },
            {{48, 100, -31}, {101, 101, 116}, {102, 122, 47}, },
            {{48, 114, -51}, {115, 115, 117}, {116, 122, 47}, },
            {{48, 122, -21}, },
            {{48, 109, -59}, {110, 110, 118}, {111, 122, 47}, },
            {{48, 100, -31}, {101, 101, 119}, {102, 122, 47}, },
            {{9, 32, -81}, {91, 91, 102}, },
            {{9, 91, -102}, },
            {{9, 9, 120}, {32, 32, 121}, {93, 93, 122}, },
            {{48, 115, -22}, {116, 116, 123}, {117, 122, 47}, },
            {{48, 122, -21}, },
            {{48, 104, -60}, {105, 105, 124}, {106, 122, 47}, },
            {{48, 113, -50}, {114, 114, 125}, {115, 122, 47}, },
            {{48, 104, -60}, {105, 105, 126}, {106, 122, 47}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 100, -31}, {101, 101, 127}, {102, 122, 47}, },
            {{0, 65535, -92}, },
            {{0, 41, 90}, {42, 42, 113}, {43, 65535, -70}, },
            {{48, 102, -82}, {103, 103, 128}, {104, 122, 47}, },
            {{48, 95, -21}, {97, 108, 47}, {109, 109, 129}, {110, 122, 47}, },
            {{48, 95, -21}, {97, 97, 130}, {98, 122, 47}, },
            {{48, 122, -21}, },
            {{48, 99, -90}, {100, 100, 131}, {101, 122, 47}, },
            {{48, 122, -21}, },
            {{9, 93, -104}, },
            {{9, 93, -104}, },
            {},
            {{48, 103, -37}, {104, 104, 132}, {105, 122, 47}, },
            {{48, 95, -21}, {97, 98, 47}, {99, 99, 133}, {100, 122, 47}, },
            {{48, 109, -59}, {110, 110, 134}, {111, 122, 47}, },
            {{48, 98, -126}, {99, 99, 135}, {100, 122, 47}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{46, 46, 136}, {48, 122, -21}, },
            {{48, 109, -59}, {110, 110, 137}, {111, 122, 47}, },
            {{48, 114, -51}, {115, 115, 138}, {116, 122, 47}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{111, 111, 139}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{117, 117, 140}, },
            {{116, 116, 141}, },
            {{46, 46, 142}, },
            {{112, 112, 143}, },
            {{114, 114, 144}, },
            {{105, 105, 145}, },
            {{110, 110, 146}, },
            {{116, 116, 147}, },
            {{108, 108, 148}, },
            {{110, 110, 149}, },
            {},
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {-1, 37, 37, 37, 37, 36, -1, 1, 2, 30, 28, 20, 29, 21, -1, 0, 19, 27, 25, 39, 39, 3, 4, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 5, 6, 37, 26, -1, -1, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 7, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, -1, -1, -1, 38, 38, 39, 39, 39, 39, 39, 39, 39, 15, 39, 39, 35, 39, 39, 39, 39, 39, 39, 39, -1, 38, 38, 39, 39, 39, 39, 8, 39, 39, -1, -1, -1, 39, 13, 39, 39, 39, 34, 32, 12, 39, -1, -1, 39, 39, 39, 9, 39, 33, -1, -1, 16, 39, 39, 39, 39, 23, 14, 39, 39, 39, 31, 10, 22, 11, -1, 17, 18, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 24, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
