/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.node;

import minijava.analysis.*;

@SuppressWarnings("nls")
public final class TTokExtends extends Token
{
    public TTokExtends()
    {
        super.setText("extends");
    }

    public TTokExtends(int line, int pos)
    {
        super.setText("extends");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTokExtends(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTokExtends(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTokExtends text.");
    }
}
