/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.node;

import minijava.analysis.*;

@SuppressWarnings("nls")
public final class TTokString extends Token
{
    public TTokString()
    {
        super.setText("String");
    }

    public TTokString(int line, int pos)
    {
        super.setText("String");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTokString(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTokString(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTokString text.");
    }
}
