/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.node;

import minijava.analysis.*;

@SuppressWarnings("nls")
public final class TTokSyso extends Token
{
    public TTokSyso()
    {
        super.setText("System.out.println");
    }

    public TTokSyso(int line, int pos)
    {
        super.setText("System.out.println");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTokSyso(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTokSyso(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTokSyso text.");
    }
}
