/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.node;

import minijava.analysis.*;

@SuppressWarnings("nls")
public final class ANewArrayExp extends PExp
{
    private PExp _size_;

    public ANewArrayExp()
    {
        // Constructor
    }

    public ANewArrayExp(
        @SuppressWarnings("hiding") PExp _size_)
    {
        // Constructor
        setSize(_size_);

    }

    @Override
    public Object clone()
    {
        return new ANewArrayExp(
            cloneNode(this._size_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANewArrayExp(this);
    }

    public PExp getSize()
    {
        return this._size_;
    }

    public void setSize(PExp node)
    {
        if(this._size_ != null)
        {
            this._size_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._size_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._size_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._size_ == child)
        {
            this._size_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._size_ == oldChild)
        {
            setSize((PExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
