/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.node;

import minijava.analysis.*;

@SuppressWarnings("nls")
public final class ANewObjectExp extends PExp
{
    private PIdentifier _classname_;

    public ANewObjectExp()
    {
        // Constructor
    }

    public ANewObjectExp(
        @SuppressWarnings("hiding") PIdentifier _classname_)
    {
        // Constructor
        setClassname(_classname_);

    }

    @Override
    public Object clone()
    {
        return new ANewObjectExp(
            cloneNode(this._classname_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANewObjectExp(this);
    }

    public PIdentifier getClassname()
    {
        return this._classname_;
    }

    public void setClassname(PIdentifier node)
    {
        if(this._classname_ != null)
        {
            this._classname_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._classname_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._classname_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._classname_ == child)
        {
            this._classname_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._classname_ == oldChild)
        {
            setClassname((PIdentifier) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
