/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.node;

import minijava.analysis.*;

@SuppressWarnings("nls")
public final class TTokThis extends Token
{
    public TTokThis()
    {
        super.setText("this");
    }

    public TTokThis(int line, int pos)
    {
        super.setText("this");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTokThis(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTokThis(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTokThis text.");
    }
}
