/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.node;

import minijava.analysis.*;

@SuppressWarnings("nls")
public final class TTokStatic extends Token
{
    public TTokStatic()
    {
        super.setText("static");
    }

    public TTokStatic(int line, int pos)
    {
        super.setText("static");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTokStatic(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTokStatic(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTokStatic text.");
    }
}
