/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.node;

import minijava.analysis.*;

@SuppressWarnings("nls")
public final class TTokNew extends Token
{
    public TTokNew()
    {
        super.setText("new");
    }

    public TTokNew(int line, int pos)
    {
        super.setText("new");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTokNew(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTokNew(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTokNew text.");
    }
}
