/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.node;

import minijava.analysis.*;

@SuppressWarnings("nls")
public final class TTokMain extends Token
{
    public TTokMain()
    {
        super.setText("main");
    }

    public TTokMain(int line, int pos)
    {
        super.setText("main");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTokMain(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTokMain(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTokMain text.");
    }
}
